version: 1.1.{build}
image: Visual Studio 2017
build:
  verbosity: minimal
configuration:
  - Release
before_build:
  - .paket\paket.bootstrapper.exe
  - .paket\paket.exe restore
after_build:
  - cd JournalTest\bin\Release
  - JournalTest.exe
  - cd ..\..\..
